package uas;

import java.io.*;
import java.awt.*;
import javax.swing.*;
import java.util.*;

public class NewJFrame extends javax.swing.JFrame {
    private String angka;
    private String operasi;
    private double input;
    private double jumlah;
    private double mix;
    private double bil1;
    private double bil2;
    private int pilih;
    
    
    public NewJFrame() {
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tampilHasil = new javax.swing.JTextField();
        btnBagi = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnSamaDengan = new javax.swing.JButton();
        angka9 = new javax.swing.JButton();
        angka6 = new javax.swing.JButton();
        angka3 = new javax.swing.JButton();
        btnKoma = new javax.swing.JButton();
        angka8 = new javax.swing.JButton();
        angka5 = new javax.swing.JButton();
        angka2 = new javax.swing.JButton();
        angka0 = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        angka7 = new javax.swing.JButton();
        angka4 = new javax.swing.JButton();
        angka1 = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        tampilHasil.setBackground(new java.awt.Color(0, 0, 0));
        tampilHasil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tampilHasil.setForeground(new java.awt.Color(255, 255, 255));
        tampilHasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tampilHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilHasilActionPerformed(evt);
            }
        });

        btnBagi.setBackground(new java.awt.Color(0, 0, 0));
        btnBagi.setForeground(new java.awt.Color(204, 153, 255));
        btnBagi.setText("/");
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });

        btnKali.setBackground(new java.awt.Color(0, 0, 0));
        btnKali.setForeground(new java.awt.Color(0, 204, 204));
        btnKali.setText("x");
        btnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaliActionPerformed(evt);
            }
        });

        btnKurang.setBackground(new java.awt.Color(0, 0, 0));
        btnKurang.setForeground(new java.awt.Color(0, 204, 204));
        btnKurang.setText("-");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 0, 0));
        btnTambah.setForeground(new java.awt.Color(0, 204, 204));
        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSamaDengan.setBackground(new java.awt.Color(255, 153, 0));
        btnSamaDengan.setForeground(new java.awt.Color(255, 255, 255));
        btnSamaDengan.setText("=");
        btnSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamaDenganActionPerformed(evt);
            }
        });

        angka9.setBackground(new java.awt.Color(0, 0, 0));
        angka9.setForeground(new java.awt.Color(255, 255, 255));
        angka9.setText("9");
        angka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka9ActionPerformed(evt);
            }
        });

        angka6.setBackground(new java.awt.Color(0, 0, 0));
        angka6.setForeground(new java.awt.Color(255, 255, 255));
        angka6.setText("6");
        angka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka6ActionPerformed(evt);
            }
        });

        angka3.setBackground(new java.awt.Color(0, 0, 0));
        angka3.setForeground(new java.awt.Color(255, 255, 255));
        angka3.setText("3");
        angka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka3ActionPerformed(evt);
            }
        });

        btnKoma.setBackground(new java.awt.Color(0, 0, 0));
        btnKoma.setForeground(new java.awt.Color(255, 255, 255));
        btnKoma.setText(".");
        btnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomaActionPerformed(evt);
            }
        });

        angka8.setBackground(new java.awt.Color(0, 0, 0));
        angka8.setForeground(new java.awt.Color(255, 255, 255));
        angka8.setText("8");
        angka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka8ActionPerformed(evt);
            }
        });

        angka5.setBackground(new java.awt.Color(0, 0, 0));
        angka5.setForeground(new java.awt.Color(255, 255, 255));
        angka5.setText("5");
        angka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka5ActionPerformed(evt);
            }
        });

        angka2.setBackground(new java.awt.Color(0, 0, 0));
        angka2.setForeground(new java.awt.Color(255, 255, 255));
        angka2.setText("2");
        angka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka2ActionPerformed(evt);
            }
        });

        angka0.setBackground(new java.awt.Color(0, 0, 0));
        angka0.setForeground(new java.awt.Color(255, 255, 255));
        angka0.setText("0");
        angka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka0ActionPerformed(evt);
            }
        });

        btnDeleteAll.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteAll.setForeground(new java.awt.Color(255, 255, 102));
        btnDeleteAll.setText("AC");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        angka7.setBackground(new java.awt.Color(0, 0, 0));
        angka7.setForeground(new java.awt.Color(255, 255, 255));
        angka7.setText("7");
        angka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka7ActionPerformed(evt);
            }
        });

        angka4.setBackground(new java.awt.Color(0, 0, 0));
        angka4.setForeground(new java.awt.Color(255, 255, 255));
        angka4.setText("4");
        angka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka4ActionPerformed(evt);
            }
        });

        angka1.setBackground(new java.awt.Color(0, 0, 0));
        angka1.setForeground(new java.awt.Color(255, 255, 255));
        angka1.setText("1");
        angka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka1ActionPerformed(evt);
            }
        });

        btnPlusMinus.setBackground(new java.awt.Color(0, 0, 0));
        btnPlusMinus.setForeground(new java.awt.Color(102, 255, 102));
        btnPlusMinus.setText("+/-");
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 102));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tampilHasil)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(angka7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(angka4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(angka5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(angka8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(angka0, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSamaDengan, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(btnPlusMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampilHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnBagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(angka9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(angka7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(angka8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(angka4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(angka6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(angka5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angka3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(angka0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        setBil1(Double.parseDouble(getTampilHasil().getText()));
        setMix(getMix() - getBil1());
        getTampilHasil().setText("");
        setOperasi("-");
        setPilih(2);
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        setBil1(Double.parseDouble(getTampilHasil().getText()));
        setMix(getMix() / getBil1());
        getTampilHasil().setText("");
        setOperasi("/");
        setPilih(4); 
    }//GEN-LAST:event_btnBagiActionPerformed

    private void angka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka9ActionPerformed
        String angka = getTampilHasil().getText() + getAngka9().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka9ActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        setBil1(Double.parseDouble(getTampilHasil().getText()));
        setMix(getMix() * getBil1());
        getTampilHasil().setText("");
        setOperasi("*");
        setPilih(3);
    }//GEN-LAST:event_btnKaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        setBil1(Double.parseDouble(getTampilHasil().getText()));
        setMix(getMix() + getBil1());
        getTampilHasil().setText("");
        setOperasi("+");
        setPilih(1);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamaDenganActionPerformed

        try {
            switch (getPilih()) {
                case 1:
                    setInput(Double.parseDouble(getTampilHasil().getText()));
                    setJumlah(getMix() + getInput());
                    setAngka(String.valueOf(getJumlah()));
                    setMix(getMix() + getInput());
                    getTampilHasil().setText(getAngka());
                    setMix(0);
                    break;
                case 2:
                    setInput(Double.parseDouble(getTampilHasil().getText()));
                    setJumlah(getJumlah() - getInput());
                    setAngka(Double.toString(getJumlah()));
                    setMix(getMix() - getInput());
                    getTampilHasil().setText(getAngka());
                    setMix(0);
                    break;
                case 3:
                    setInput(Double.parseDouble(getTampilHasil().getText()));
                    setJumlah(getJumlah() * getInput());
                    setAngka(Double.toString(getJumlah()));
                    setMix(getMix() * getInput());
                    getTampilHasil().setText(getAngka());
                    setMix(0);
                    break;
                case 4:
                    setInput(Double.parseDouble(getTampilHasil().getText()));
                    setJumlah(getJumlah() / getInput());
                    setAngka(Double.toString(getJumlah()));
                    setMix(getMix() / getInput());
                    getTampilHasil().setText(getAngka());
                    setMix(0);
                    break;
            }
        } catch (NumberFormatException | ArithmeticException ex) {
            // Handle the exception (e.g., display an error message)
            System.out.println("Invalid input or division by zero: Please enter a valid number.");
        }
    }
    //GEN-LAST:event_btnSamaDenganActionPerformed

    private void angka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka0ActionPerformed
        String angka = getTampilHasil().getText() + getAngka0().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka0ActionPerformed

    private void angka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka1ActionPerformed
        String angka = getTampilHasil().getText() + getAngka1().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka1ActionPerformed

    private void angka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka2ActionPerformed
        String angka = getTampilHasil().getText() + getAngka2().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka2ActionPerformed

    private void angka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka4ActionPerformed
        String angka = getTampilHasil().getText() + getAngka4().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka4ActionPerformed

    private void angka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka5ActionPerformed
        String angka = getTampilHasil().getText() + getAngka5().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka5ActionPerformed

    private void angka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka8ActionPerformed
         setAngka(getAngka() + "8");
        getTampilHasil().setText(getAngka());
    }//GEN-LAST:event_angka8ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int length = getTampilHasil().getText().length();
        int angka = getTampilHasil().getText().length() - 1;
        String store;
        if(length > 0){
            StringBuilder back = new StringBuilder(getTampilHasil().getText());
            back.deleteCharAt(angka);
            store = back.toString();
            getTampilHasil().setText(store);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        double ops = Double.parseDouble(String.valueOf(getTampilHasil().getText()));
        ops = ops * (-1);
        getTampilHasil().setText(String.valueOf(ops));
    }//GEN-LAST:event_btnPlusMinusActionPerformed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        getTampilHasil().setText(getAngka());
        setBil1(0);
        setBil2(0);
        setJumlah(0);
        setMix(0);
        setAngka("");
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void angka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka3ActionPerformed
        String angka = getTampilHasil().getText() + getAngka3().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka3ActionPerformed

    private void angka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka6ActionPerformed
        String angka = getTampilHasil().getText() + getAngka6().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka6ActionPerformed

    private void angka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka7ActionPerformed
        String angka = getTampilHasil().getText() + getAngka7().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_angka7ActionPerformed

    private void tampilHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilHasilActionPerformed

    private void btnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomaActionPerformed
        String angka = getTampilHasil().getText() + getBtnKoma().getText();
        getTampilHasil().setText(angka);
    }//GEN-LAST:event_btnKomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //objek
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton angka0;
    private javax.swing.JButton angka1;
    private javax.swing.JButton angka2;
    private javax.swing.JButton angka3;
    private javax.swing.JButton angka4;
    private javax.swing.JButton angka5;
    private javax.swing.JButton angka6;
    private javax.swing.JButton angka7;
    private javax.swing.JButton angka8;
    private javax.swing.JButton angka9;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKoma;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnSamaDengan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField tampilHasil;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the angka
     */
    public String getAngka() {
        return angka;
    }

    /**
     * @param angka the angka to set
     */
    public void setAngka(String angka) {
        this.angka = angka;
    }

    /**
     * @return the operasi
     */
    public String getOperasi() {
        return operasi;
    }

    /**
     * @param operasi the operasi to set
     */
    public void setOperasi(String operasi) {
        this.operasi = operasi;
    }

    /**
     * @return the input
     */
    public double getInput() {
        return input;
    }

    /**
     * @param input the input to set
     */
    public void setInput(double input) {
        this.input = input;
    }

    /**
     * @return the jumlah
     */
    public double getJumlah() {
        return jumlah;
    }

    /**
     * @param jumlah the jumlah to set
     */
    public void setJumlah(double jumlah) {
        this.jumlah = jumlah;
    }

    /**
     * @return the mix
     */
    public double getMix() {
        return mix;
    }

    /**
     * @param mix the mix to set
     */
    public void setMix(double mix) {
        this.mix = mix;
    }

    /**
     * @return the bil1
     */
    public double getBil1() {
        return bil1;
    }

    /**
     * @param bil1 the bil1 to set
     */
    public void setBil1(double bil1) {
        this.bil1 = bil1;
    }

    /**
     * @return the bil2
     */
    public double getBil2() {
        return bil2;
    }

    /**
     * @param bil2 the bil2 to set
     */
    public void setBil2(double bil2) {
        this.bil2 = bil2;
    }

    /**
     * @return the pilih
     */
    public int getPilih() {
        return pilih;
    }

    /**
     * @param pilih the pilih to set
     */
    public void setPilih(int pilih) {
        this.pilih = pilih;
    }

    /**
     * @return the angka0
     */
    public javax.swing.JButton getAngka0() {
        return angka0;
    }

    /**
     * @param angka0 the angka0 to set
     */
    public void setAngka0(javax.swing.JButton angka0) {
        this.angka0 = angka0;
    }

    /**
     * @return the angka1
     */
    public javax.swing.JButton getAngka1() {
        return angka1;
    }

    /**
     * @param angka1 the angka1 to set
     */
    public void setAngka1(javax.swing.JButton angka1) {
        this.angka1 = angka1;
    }

    /**
     * @return the angka2
     */
    public javax.swing.JButton getAngka2() {
        return angka2;
    }

    /**
     * @param angka2 the angka2 to set
     */
    public void setAngka2(javax.swing.JButton angka2) {
        this.angka2 = angka2;
    }

    /**
     * @return the angka3
     */
    public javax.swing.JButton getAngka3() {
        return angka3;
    }

    /**
     * @param angka3 the angka3 to set
     */
    public void setAngka3(javax.swing.JButton angka3) {
        this.angka3 = angka3;
    }

    /**
     * @return the angka4
     */
    public javax.swing.JButton getAngka4() {
        return angka4;
    }

    /**
     * @param angka4 the angka4 to set
     */
    public void setAngka4(javax.swing.JButton angka4) {
        this.angka4 = angka4;
    }

    /**
     * @return the angka5
     */
    public javax.swing.JButton getAngka5() {
        return angka5;
    }

    /**
     * @param angka5 the angka5 to set
     */
    public void setAngka5(javax.swing.JButton angka5) {
        this.angka5 = angka5;
    }

    /**
     * @return the angka6
     */
    public javax.swing.JButton getAngka6() {
        return angka6;
    }

    /**
     * @param angka6 the angka6 to set
     */
    public void setAngka6(javax.swing.JButton angka6) {
        this.angka6 = angka6;
    }

    /**
     * @return the angka7
     */
    public javax.swing.JButton getAngka7() {
        return angka7;
    }

    /**
     * @param angka7 the angka7 to set
     */
    public void setAngka7(javax.swing.JButton angka7) {
        this.angka7 = angka7;
    }

    /**
     * @return the angka8
     */
    public javax.swing.JButton getAngka8() {
        return angka8;
    }

    /**
     * @param angka8 the angka8 to set
     */
    public void setAngka8(javax.swing.JButton angka8) {
        this.angka8 = angka8;
    }

    /**
     * @return the angka9
     */
    public javax.swing.JButton getAngka9() {
        return angka9;
    }

    /**
     * @param angka9 the angka9 to set
     */
    public void setAngka9(javax.swing.JButton angka9) {
        this.angka9 = angka9;
    }

    /**
     * @return the btnDelete
     */
    public javax.swing.JButton getBtnDelete() {
        return btnDelete;
    }

    /**
     * @param btnDelete the btnDelete to set
     */
    public void setBtnDelete(javax.swing.JButton btnDelete) {
        this.btnDelete = btnDelete;
    }
    
    /**
     * @return the btnKoma
     */
    public javax.swing.JButton getBtnKoma() {
        return btnKoma;
    }

    /**
     * @param btnKoma the btnKoma to set
     */
    public void setBtnKoma(javax.swing.JButton btnKoma) {
        this.btnKoma = btnKoma;
    }

    /**
     * @return the btnPlusMinus
     */
    public javax.swing.JButton getBtnPlusMinus() {
        return btnPlusMinus;
    }

    /**
     * @param btnPlusMinus the btnPlusMinus to set
     */
    public void setBtnPlusMinus(javax.swing.JButton btnPlusMinus) {
        this.btnPlusMinus = btnPlusMinus;
    }

    /**
     * @return the btnSamaDengan
     */
    public javax.swing.JButton getBtnSamaDengan() {
        return btnSamaDengan;
    }

    /**
     * @param btnSamaDengan the btnSamaDengan to set
     */
    public void setBtnSamaDengan(javax.swing.JButton btnSamaDengan) {
        this.btnSamaDengan = btnSamaDengan;
    }

    /**
     * @return the tampilHasil
     */
    public javax.swing.JTextField getTampilHasil() {
        return tampilHasil;
    }

    /**
     * @param tampilHasil the tampilHasil to set
     */
    public void setTampilHasil(javax.swing.JTextField tampilHasil) {
        this.tampilHasil = tampilHasil;
    }
}
